---
CommitMsg:
  HardTabs:
    enabled: true
PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail
  BundleAudit:
    enabled: true
  BundleCheck:
    enabled: true
  BundleOutdated:
    enabled: true
  ExecutePermissions:
    enabled: true
    exclude:
      - bin/*
  ForbiddenBranches:
    enabled: true
    branch_patterns: master
  HardTabs:
    enabled: true
  JsonSyntax:
    enabled: true
  LineEndings:
    enabled: true
    eol: "\n"
  Mdl:
    enabled: true
  TrailingWhitespace:
    enabled: true
  YamlLint:
    enabled: true
  YamlSyntax:
    enabled: true
